### ISSUE TITLE
Feature Request: Integrated Prometheus Metrics Exporter

### ISSUE THREAD

**Issue by kouvaliasnick** [mycrl/turn-rs#101]
**Is your feature request related to a problem? Please describe.**
We're migrating from `coturn` to `turn-rs` for its superior performance, but we're missing the ability to monitor server health and performance metrics. Currently, there's no built-in way to expose metrics to Prometheus, which makes it difficult to:
- Monitor server health
- Track resource usage
- Debug performance issues
- Set up alerts for potential problems

**Describe the solution you'd like**
An integrated Prometheus metrics exporter similar to what `coturn` provides. Key metrics we'd like to see:
- Total/active allocations
- Bytes sent/received
- Packets sent/received
- Protocol-specific metrics (UDP/TCP/TLS)
- Session duration
- Error counts

Ideally exposed on a `/metrics` endpoint in standard Prometheus format.

**Describe alternatives you've considered**
- Using system-level metrics only (less accurate/useful)

**Additional context**
We're using turn-rs in a production environment where monitoring is crucial for maintaining service reliability.

**Comment by mycrl** [comment]
The existing http api can provide this information you want, so you can expose it to Prometheus yourself.
However, your feature request is not unnecessary, so I will add support for exporting to Prometheus.

**Comment by mycrl** [comment]
@kouvaliasnick I looked into Prometheus exporter and it looks like it needs to export all the data at once, which may not be very acceptable for turn-rs. turn-rs metrics are for individual sessions, and to export them all at once would require traversing all the sessions and collecting the data, which is not acceptable for turn-rs.

Because turn-rs does not have a database, all access to the api is required to go through the collection process, which means that there is no cache, a normal turn server one-time existence of several thousand sessions is very normal, a metrics acquisition may be the server's internal mutex locks generate a great deal of overhead.

I would recommend that you can receive push from the turn server via the HTTP api currently provided by turn-rs and get the metrics updated to the database in your service on demand and export the metrics data in your service.

Of course, if you know that you can have prometheus generate metrics data individually for each session, let me know.

I won't be adding support for this feature in this release and will be turning off this feature request for the time being. But if you know of a way to make it easier, please let me know and I'll be happy to provide support.

I'm not a professional backend developer, and although I did backend development for two years in my early days, I've been out of touch for a long time, so I know very little about these modern backend infrastructures.

**Comment by lherman-cs** [comment]
Generally, you don't want to expose high cardinal metrics like Session, as you mentioned this will not scale on the client, but also on the storage side. 

Can we do a hybrid approach instead? For high-level metrics or aggregated metrics such as total allocations, packets sent, total session duration, etc, it'll be useful to expose this with Prometheus for standard monitoring systems to ingest the data as alerts and dashboards. Since we're only tracking high-level metrics, there's no need to lock these sessions. turn-rs can have a global set of atomic counters that can get incremented as it sees usages. Then, as the Prometheus poll interval kicks in, turn-rs can pull the metrics from this global set of atomic counters. The extra CPU and memory usage should be minimal.

For any high cardinal metrics, we need to keep them as HTTP hooks instead. An external analytics system has to ingest this efficiently.

**Comment by mycrl** [comment]
Thanks, I'm going to re-add support, I misunderstood what you were starting to want.

If it's just wanting some aggregate stats, then it's still easy to provide support.

It's just that I'm rather confused as to how much monitoring help these vague stats can provide. Sorry... I don't start backend services... So don't quite understand...

**Comment by lherman-cs** [comment]
@mycrl got it. I can provide some use cases here.

**Case 1: detecting system-wide issues**

Typically, traffic patterns are similar either daily or weekly. So, it's useful to see if the current traffic pattern doesn't follow similarly to what we expect. So, we can create something like anomaly detection using lite machine learning. Some metric collectors have done this natively. netdata is one example, https://www.netdata.cloud/.

In this case, we can use Total/active allocations or Bytes sent/received, or any metrics that can be used as proxy success metrics.

**Case 2: load balance nodes**

Balancing for bandwidth usage per node:

Many cloud providers offer free bandwidth alongside the VM. While businesses can opt to pay for extra bandwidth, it's more cost-effective to stay within the free allowance. For example, if I have used up all of my bandwidth for node A, I can redirect future traffic to node B until my free allowance resets.

Network Throughput Bottleneck:

This is a preventive approach to make sure no single node serves traffic near the link throughput or handling too many sessions. Handling too many sessions can have inherent problems where the TURN server might need to burst a bunch of packets at the same time. If a frame requires 200 packets in a burst and there are 1,000 sessions, the chance of needing to burst these packets at the same time is higher, the turn server will likely introduce delay much earlier than the network capacity. So, a business can decide to reduce this likelihood by load balancing based on the Prometheus feedback. 

**Case 3: Business KPI**

This can be either for developers or businesses. It's useful to know how much traffic goes to these turn services as these data can be used as KPI metrics that can be shared with the other customers to build trust.

**Comment by mycrl** [comment]
done: https://github.com/mycrl/turn-rs/pull/106
