### ISSUE TITLE
CreatePermission 403 Forbidden

### ISSUE THREAD

**Issue by lherman-cs** [mycrl/turn-rs#103]
This project is awesome! I had a nice time reading the codebase and particularly enjoyed the separation of `turn` vs `turn-server.

**Describe the bug**
I was able to receive the reflexive candidate from the TURN service. However, when my client tried to create a binding or CreatePermission request, The turn server responded with 403 Forbidden.

**To Reproduce**
My TURN setup currently is the following:

1. Compile from the latest main: https://github.com/mycrl/turn-rs/commit/f113b2b42bbc926e715c6bac36b3dead1a04482e
2. Configure so the bind port listens to `0.0.0.0:3478` and the external IP is set to `<external>:3478`. The transport is set to UDP.
3. Static auth config is `demo=demo`.
4. The server ran without any containerization, just a barebone binary. The instance also has direct access to an external IP.
5. Use either https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/ or https://github.com/pion/turn/tree/master/examples/turn-client/udp to run a ping test.

**Expected behavior**
TURN server to allow the allocation and let the media flow.

**Additional context**
From tracing the codebase, these lines caused the issue, https://github.com/mycrl/turn-rs/blob/main/turn/src/processor/create_permission.rs#L93-L99.

I didn't see anything in RFC that defines this behavior as a MUST. So, I'm expecting that there are some specific reasons for this implementation.

**Regarding `ip_is_local`:**

`ctx` contains my server's external IPs, whereas `peer` contains the reflexive IP. But, with `!ip_is_local` (as the name implies), the TURN server will always reject external IPs.

**Then, I tried commenting out `ip_is_local` check:**

I found that the `bind_port` look ups for the peer's port whereas the allocation used the server's port instead, https://github.com/mycrl/turn-rs/blob/main/turn/src/processor/allocate.rs#L88-L91.

Thus, `bind_port` also couldn't find anything and ended with another 403 Forbidden.

**Comment by mycrl** [comment]
Thank you, I am happy with how my program has helped you.

First of all, I'm not complaining that your proposed problem doesn't exist or is boring, and I hope my tone doesn't bother you. This project has been pretty much tried and tested for standard stun and turn session processes, including having been used in many business systems for a long time, so there shouldn't be too many problems with basic business turn-rs.
Next, I'll walk you through troubleshooting the problem step-by-step.

First of all, the `ip_is_local` part that you brought up in your question, the meaning of this check is that if an illegitimate turn request is received, such as requesting an address that doesn't belong to the current turn server, it should be rejected, which really doesn't belong to the RFC, but this is a defensive process, and turn servers are supposed to be rejecting illegitimate requests, since It is not possible to create permissions or bind peers for requests that do not belong to the current turn server.

First, do you have your external address set to an external address, but your connectivity test is using a local address such as `127.0.0.1`, which would cause turn-rs to reject your request due to an external mismatch. Because in this case, the turn client will most likely also set the external address to `127.0.0.1` when constructing the turn request, so `ip_is_local` won't get through here, I'm not sure if other implementations of turn servers allow for this, but it seems to be reasonable for me to do it this way. I'm guessing that's most likely the case with your problem.

Secondly, you can try to run turn-rs in a local environment with both bind and external configured to `127.0.0.1` and test if it passes, if it passes, then the problem is the situation I have already mentioned above.

For example, when your `external` address is set to `192.168.1.100`, then the turn client should need to use `turn:192.168.1.100:3478` when communicating with the turn server.

**Comment by mycrl** [comment]
I tested it locally and didn't check that there was a problem.

I tested using trickle ice as well, with the turn server running locally and the config file using the example config file from the project, and didn't change anything else except uncommenting `user1=test`.

![{459ABBC4-C800-4DFF-A799-B95DB0B4157E}](https://github.com/user-attachments/assets/804f3fdc-f214-490a-8336-25b523f3612d)

This is my test result, which has successfully assigned the address and created the permissions

![{58218D6E-2AC0-4B67-819E-3A313C678C28}](https://github.com/user-attachments/assets/1e1af9f9-0064-40cb-be6d-0996a0ae68d2)

![{0AAFD488-3B6F-45C7-A753-40E4343BE741}](https://github.com/user-attachments/assets/fcd8ca06-06d4-405e-85bf-b46ddbd18724)

**Comment by mycrl** [comment]
I'll test it again with https://github.com/firefart/stunner, and let me know if you have more info on it as well, because I recently posted a new version that was not in the production environment with a few changes, which theoretically shouldn't be a problem, but maybe I changed something to cause a problem with the new version .

**Comment by mycrl** [comment]
@lherman-cs I simply wrote a webrtc test page to force the use of turn forwards to create rtc, I tested it and found no problems.
Can you provide your wireshark dump file if it's convenient? If you don't want your web information to be compromised, you can send it to my private email: lepidodendraceae@gmail.com
