### ISSUE TITLE
 Missing timestamp validation in TURN REST API authentication

### ISSUE THREAD

**Issue by DDreame** [mycrl/turn-rs#108]
According to [draft-uberti-behave-turn-rest-00 Section 2.2](https://datatracker.ietf.org/doc/html/draft-uberti-behave-turn-rest-00#section-2.2), the TURN username should be a colon-delimited combination of:
- Expiration timestamp
- Username parameter from the request

Currently in `publicly.rs`, the `encode_password` function or the `get_password` function doesn't implement this timestamp validation. The timestamp should be prepended to the username before generating the HMAC-SHA1.

Example format should be: `timestamp:username`

I can submit a PR to implement this if needed. This would improve security by adding expiration validation to credentials.

**Comment by mycrl** [comment]
I didn't verify the timestamp, but you're welcome to add timestamp verification.

I took a rather tricky approach to this validation, in fact, in the `get_password` function, the format of `name` is already `timestamp:username`, because the `username` attribute in the stun message is already formatted that way.

So I'm treating the whole string `timestamp:username` as a username, which makes logical sense, I'm just not validating the timestamp expiration date.

I don't really recommend adding `timestamp` to `encode_password` to generate it, since `timestamp` already exists for the username passed by the client. However, it is possible to split out the `timestamp` in the username when validating the `static_auth_secret` to validate the expiration date, and the `encode_password` doesn't need to be changed.

**Comment by DDreame** [comment]
> I didn't verify the timestamp, but you're welcome to add timestamp verification.
> 
> I took a rather tricky approach to this validation, in fact, in the `get_password` function, the format of `name` is already `timestamp:username`, because the `username` attribute in the stun message is already formatted that way.
> 
> So I'm treating the whole string `timestamp:username` as a username, which makes logical sense, I'm just not validating the timestamp expiration date.
> 
> I don't really recommend adding `timestamp` to `encode_password` to generate it, since `timestamp` already exists for the username passed by the client. However, it is possible to split out the `timestamp` in the username when validating the `static_auth_secret` to validate the expiration date, and the `encode_password` doesn't need to be changed.

Ok, I understand. So can I validating  the timestamp on the [`get_password`](https://github.com/mycrl/turn-rs/blob/main/turn-server/src/publicly.rs#L242) function and before the auth `static_auth_secret` ? 

Maybe I still need to consider not verifying if there is no timestamp, and verifying if there is a timestamp.

**Comment by mycrl** [comment]
https://github.com/mycrl/turn-rs/blob/main/turn-server/src/publicly.rs#L248

Simply insert validation here and determine if the username contains a timestamp and if it is expired before encoding the password.

However, it should be noted that some clients may not strictly adhere to this protocol as it is only a draft and has not yet been stabilized, so the timestamp is likely to be a random number. However, since we have added timestamp validation, there is no need to consider this incompatibility.

**Comment by DDreame** [comment]
Great! I will create a pr soon.
