### ISSUE TITLE
Is it possible to setting up turn-rs sever on the local network for testing?

### ISSUE THREAD

**Issue by Razzwan** [mycrl/turn-rs#115]
**Is your feature request related to a problem? Please describe.**
I am trying to set up a test site on a local network. The task is to connect and disconnect users to a video conference according to certain rules. To test this rather complex logic, the most reasonable thing to do is to set up testing on a local network of 20 devices. The question is, is this even possible? So far I haven't been able to set this up on a loyal network.

**Describe the solution you'd like**
A clear and concise approach to setup turn-rs in local environment and local network for testing purpose

**Describe alternatives you've considered**
Alternativa is a use server with static IP address

**Additional context**
Maybe I'm the only one who's so stupid, but I've been trying to set up work on the local network for the second day and have not achieved any success so far

**Comment by mycrl** [comment]
Local testing is possible, but not in a `localhost` environment.
You can test under local LAN, it doesn't matter.

By the way, turn-rs is currently working on some bug fixes, the previous version didn't work properly for some clients in local network environment. This is due to the fact that turn-rs does not implement the RFCs correctly, which does not affect most scenarios and clients, but it does not work for some clients in local network environments.

**Comment by Razzwan** [comment]
Thank you for your answer. 

Actually, I am using this `ghcr.io/mycrl/turn-server` docker version. Seems like everything works fine in local network (at least regarding stun server). It was just my mistake with signaling server. Thank you very mucth for such grate package. It is realy simple and works better then coturn. The only thing I would like to figure out, how to use my own users from database for auth turn server, but it is a separate story...

Thank you

**Comment by mycrl** [comment]
Glad I could help.
