### ISSUE TITLE
Question: how are external and bind supposed to differ?

### ISSUE THREAD

**Issue by Kladki** [mycrl/turn-rs#90]
I have a dynamic IP address, so I cannot set my IP address in the config file ahead of time, so what should I do? Also, what is the point of the `external` field, isn't `bind` enough?

**Comment by mycrl** [comment]
> I have a dynamic IP address, so I cannot set my IP address in the config file ahead of time, so what should I do? Also, what is the point of the `external` field, isn't `bind` enough?

bind is used to bind to the address of your local NIC, for example, you have two NICs A and B on your server, the IP address of NIC A is 192.168.1.2, and the address of NIC B is 192.168.1.3, if you bind to NIC A, you should bind to the address of 192.168.1.2, and bind to 0.0.0.0 means that it listens to all of them at the same time.

external is that your network card for the client can "see" the ip address, continue the above example, your A network card in communication with the external, if it is in the local area network, then other clients see is your LAN address, that is, 192.168.1.2, but in reality, generally However, in reality, the network topology where the server is deployed, there will be another public ip, such as 1.1.1.1, which is your ip address seen by other clients.

As for why bind and external are needed, this is because for the stun protocol, the situation is more complicated, the stun server needs to inform its own external ip address, which allows the stun client to connect to the specified address through the ip address informed by the server.

If you are dynamic ip service, it is not suitable to deploy turn server, turn server needs a fixed ip address, this is the specification of the stun/turn protocol, not a feature that exists in this project itself.

**Comment by mycrl** [comment]
> As for why bind and external are needed, this is because for the stun protocol, the situation is more complicated, the stun server needs to inform its own external ip address, which allows the stun client to connect to the specified address through the ip address informed by the server. If you are dynamic ip service, it is not suitable to deploy turn server, turn server needs a fixed ip address, this is the specification of the stun/turn protocol, not a feature that exists in this project itself.
> Ah ok, so that is to give to the client? If so, would you be open to me adding the ability for the turn server to detect it's own public IP via [IGD](https://lib.rs/crates/igd)?

I don't really recommend to add gateway probing feature in turn server, because in reality, the network topology is complex, like the example I mentioned above, there are many cloud server providers whose networks are virtual networks, a simple example is that you can't know the public ip that you belong to in the server, but the cloud service provider they assigned one for you, and they pass through the software routing to pass the packets to your server.

And, another widely used open source turn server (coturn) does not provide a similar mechanism, but requires you to manually specify it yourself.

Of course, you can fork my code and implement this part yourself, but I would rather recommend you to implement auto-probing yourself and call my service, you can see `main.rs` and `lib.rs` in the `turn-server` directory, where `main.rs` is also just for loading configurations and initializing the logger and so on, and you can just call `lib.rs` directly. lib.rs` interface to start the turn server.

Translated with DeepL.com (free version)
